Added ability to add signed timestamp to header
savonrb/akami pull request #25
Opened 2015-11-16 10:13 UTC by eiapopeia

To do this you have to give the timestamp-option to the *wsse_signature*!
Like so:
```ruby
Savon.client({
  …
  wsse_signature:
    Akami::WSSE::Signature.new(
      Akami::WSSE::Certs.new(…),
      timestamp: true)
}
```
It is also possible to give created_at and/or expires_at like this

```ruby
Savon.client({
  …
  wsse_signature:
    Akami::WSSE::Signature.new(
      Akami::WSSE::Certs.new(…),
      {timestamp: true,
      created_at: Time.now-10,
      expires_at: Time.now + 600})
}
```

2015-12-17 23:06 UTC, nathanaeljones commented
This would be extremely useful!

2015-12-18 21:50 UTC, nathanaeljones commented
Savon::Builder#build_document needs to create the headers 3 times instead of 2. I.e, replace "2.do" with "3.do" I do not yet know why.  For some reason Signature#document needs to be mutated that many times.

2015-12-18 23:32 UTC, nathanaeljones commented
One can call build_document an extra time before initiating the request, or add this to lib/savon/builder.rb:

    def get_xml
      tag(builder, :Envelope, namespaces_with_globals) do |xml|
        tag(xml, :Header, header_attributes) { xml << header.to_s } unless header.empty?
        if @globals[:no_message_tag]
          tag(xml, :Body, body_attributes) { xml << message.to_s }
        else
          tag(xml, :Body, body_attributes) { xml.tag!(*namespaced_message_tag) { xml << message.to_s } }
        end
      end
    end
    def build_document
      return get_xml unless @signature

      # if we have a signature sign the document
      if @signature
        @signature.document = get_xml
        2.times do
          @header = nil
          @signature.document = get_xml
        end
        return @signature.document
      end
    end

2016-11-02 02:12 UTC, brent-clintel requested changes
When implementing this code, I came across two issues.  I have suggested solutions in my comments based on what I did to get the code to work.

2016-11-02 02:12 UTC, brent-clintel commented on lib/akami/wsse/signature.rb
> +        return nil unless timestamp
Should tis be `return nil unless self.timestamp`.  It seems that `timestamp` refers to the variable in the scope of the method due tot he assignment on the next line.

2016-11-02 02:12 UTC, brent-clintel commented on lib/akami/wsse/signature.rb
> +        Base64.encode64(OpenSSL::Digest::SHA1.digest(timestamp)).strip
if `timestamp` is nil, which it can be, an exception is raised.  Should this line be ended with `... if timestamp`?

2025-05-19 11:59 UTC, kjeldahl commented
@pcai Any chance this could be merged? The conflict is really simple.
But it does need the change in Savon mentioned by @lilith in https://github.com/savonrb/akami/pull/25#issuecomment-165905389

2025-11-28 11:07 UTC, rgaufman commented
Can this be added please?

2026-09-10 14:56 UTC, pcai commented
Closing this out — thank you! This was superseded by #47, which is the updated version of the same change, so we will track it there.

2026-09-10 14:56 UTC, closed without merging